/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.Minecraft
 *  net.minecraftforge.common.MinecraftForge
 */
import net.minecraft.client.Minecraft;
import net.minecraftforge.common.MinecraftForge;

public class Class17 {
    public boolean llIllIIlIIIIlllIIlllIlIlIIIllIIllllIlIlIIllIIlIIIIIlllIIlIlIlIlIIIlIlIllIllIIllIIllIIllIIIIlIIlIllIIlIllIIIIllIIlllllllIlIllIIIlIIIIIlIllIIIIlllllIIlIIlIlllIIlIlIlIIlIIlIlIIIlIlIIlIllIIlllIIIIllIlIIlI;
    public String lIIlIlllIlIlIIIIllIlIllIlIlIIlIIlIlIlIlIIllIIlllIIIlIlIlllllIlIIIIIIllIIllllllIllllIIlIIIIllIIIIIIlIIIIlIIIIlIlIIllllIIIIIlllllIlIlllIlIIIIllIIIlllllllllIlIlIllIlllIIIIlIIIlIIIIlIlIlIllIlIllllllIlIlll;
    public int llIlllIlIllIllIIlIIIIIIIlIIlIIIlIllllIIllIIlIlllllIlllIlllIIIlIlIlllllIlIlIIIllIlIlllllIlIIlIlIIlIlIIlIIllIIIIIIlIlllIIIlIIlllIlIIIlIIlIlllllIlIllIllllIIIIlIIIIllIlIlIlIIllIIIIIIllIIlIIIlIllIIlllIllIl;
    public Class44 IIlIllIIIIIlllIIIllIIlIIIllIIIlIlIllIIIlIIlllIIlllllllIlIIIlIlIlllIIIIIIlIIIIlllIlllIlIlIIllIlllIlllllIllIIlIlllIIIllIlIIllllIIlIlIIIIIllllllIIlllIIIlIIllIlIllIIlIllllIlllIIlIIlIIlIlllIlIlIIllIIIIllII;
    static long lIllllIIIIIlIllIIIlllIIIlIIIlllIlIIIllIIlllIlIlIIIlIllIlIllIlIlIIIIllIllIIIlllIlllIIIIIIIIllIIlIIIllllIIlIIlllllIllIlIlllIIlllllllIIlIllIIlIlIllllIIlllIlIIIIIIlIlIIllllIIllIIllIllIllIlllIllIIIIIlllIlI = -8096960785762946406L;
    public Minecraft IIIlIlIlIlIllIlIlIlIIlllIlIIlIllIIlIIIIIIlllIlIIlIllIllIIlIlIllllIllIllIIlIllIIllIllIIIIlIIIlIIIllIIIlllllIlIlIIIIlIlIlllIllIIllIlIIllIlIllllIIlIIlIIIIIIIIlllIlIIIIIllIllIllIlIllllIIIIIIlIIlIlIIlIIlIl = Minecraft.func_71410_x();

    public static String Deobfuscated_by_tenonteam() {
        return "Deobfuscated by tenonteam";
    }

    public void lIIIIIlIlIlIlIIlIIlIIlIIIIlllIllIIllllIllIIIIlIlIIIIlIlIIlIlIIIIIlllIlllllllIIlIlIIIlIIlIIIlIlllIIIllIlIIIlIIllllIllIIllIIIlIIIIlIIlllllIIllIlIIIlIIIIIIllIIIIIIIIIllllIlIIlIIIIlIllIlIIllIlIIIllIlIlllI() {
        boolean bl = this.llIllIIlIIIIlllIIlllIlIlIIIllIIllllIlIlIIllIIlIIIIIlllIIlIlIlIlIIIlIlIllIllIIllIIllIIllIIIIlIIlIllIIlIllIIIIllIIlllllllIlIllIIIlIIIIIlIllIIIIlllllIIlIIlIlllIIlIlIlIIlIIlIlIIIlIlIIlIllIIlllIIIIllIlIIlI = !this.llIllIIlIIIIlllIIlllIlIlIIIllIIllllIlIlIIllIIlIIIIIlllIIlIlIlIlIIIlIlIllIllIIllIIllIIllIIIIlIIlIllIIlIllIIIIllIIlllllllIlIllIIIlIIIIIlIllIIIIlllllIIlIIlIlllIIlIlIlIIlIIlIlIIIlIlIIlIllIIlllIIIIllIlIIlI;
        if (this.llIllIIlIIIIlllIIlllIlIlIIIllIIllllIlIlIIllIIlIIIIIlllIIlIlIlIlIIIlIlIllIllIIllIIllIIllIIIIlIIlIllIIlIllIIIIllIIlllllllIlIllIIIlIIIIIlIllIIIIlllllIIlIIlIlllIIlIlIlIIlIIlIlIIIlIlIIlIllIIlllIIIIllIlIIlI) {
            this.IlIIIllIlllIllllIIllIllIIIlIlIIIllIlIIllllllIllIlIIIIlllllIIllIlllIIlIIIIIIlIllIIIIIlIIIIllIIlIIlIlIIllIIlIlIlIllIlllIIllllIllIIllIIIllIIlIIIlllIlIlIllIlIIIllIIIlIIIlllIlllIlIlIIIllIIlIlIIIIlIIIIIIllI();
            return;
        }
        this.llIIIIIIIIllIlIlIIlIIllllIlIIIllIlIIlIllIIIlIIlIlIlllIIIlIllIllIlIIIlIIIllIIIIIIIIIllIIIIIIIIlIllllIlIlIllllllIIIIIlIIlIIIlIllIIlIIIIIlllllllIlIllIllIIlIlllIIIIIllllllllIIIllllIIlllIIIlIllllIIllIIlIll();
    }

    public void IIIIIlIIIIIlIlIIIIIIlIllIIllIlIlIIllIIIllIIlIIIIIIlIlIIIIIIIIIIIIllllIllIlIlIIIlIIIIIlllIlllllIIIIlIllIIIlIllIlIlIIlIlllIIIllIlllIlIlIIlIIllIIlllllIIllllIlIllIlIllIIllIlIlIIlIIlIlIIlIllIlIlIIIlllllIll(boolean bl) {
        this.llIllIIlIIIIlllIIlllIlIlIIIllIIllllIlIlIIllIIlIIIIIlllIIlIlIlIlIIIlIlIllIllIIllIIllIIllIIIIlIIlIllIIlIllIIIIllIIlllllllIlIllIIIlIIIIIlIllIIIIlllllIIlIIlIlllIIlIlIlIIlIIlIlIIIlIlIIlIllIIlllIIIIllIlIIlI = bl;
        if (this.llIllIIlIIIIlllIIlllIlIlIIIllIIllllIlIlIIllIIlIIIIIlllIIlIlIlIlIIIlIlIllIllIIllIIllIIllIIIIlIIlIllIIlIllIIIIllIIlllllllIlIllIIIlIIIIIlIllIIIIlllllIIlIIlIlllIIlIlIlIIlIIlIlIIIlIlIIlIllIIlllIIIIllIlIIlI) {
            this.IlIIIllIlllIllllIIllIllIIIlIlIIIllIlIIllllllIllIlIIIIlllllIIllIlllIIlIIIIIIlIllIIIIIlIIIIllIIlIIlIlIIllIIlIlIlIllIlllIIllllIllIIllIIIllIIlIIIlllIlIlIllIlIIIllIIIlIIIlllIlllIlIlIIIllIIlIlIIIIlIIIIIIllI();
            return;
        }
        this.llIIIIIIIIllIlIlIIlIIllllIlIIIllIlIIlIllIIIlIIlIlIlllIIIlIllIllIlIIIlIIIllIIIIIIIIIllIIIIIIIIlIllllIlIlIllllllIIIIIlIIlIIIlIllIIlIIIIIlllllllIlIllIllIIlIlllIIIIIllllllllIIIllllIIlllIIIlIllllIIllIIlIll();
    }

    public void llIIIIIIIIllIlIlIIlIIllllIlIIIllIlIIlIllIIIlIIlIlIlllIIIlIllIllIlIIIlIIIllIIIIIIIIIllIIIIIIIIlIllllIlIlIllllllIIIIIlIIlIIIlIllIIlIIIIIlllllllIlIllIllIIlIlllIIIIIllllllllIIIllllIIlllIIIlIllllIIllIIlIll() {
        MinecraftForge.EVENT_BUS.unregister((Object)this);
    }

    public boolean llIlIlIIlIlIllIlllIlIIlllllIlllIIllIIllIlIlIIlIllIllIIIIlllllIlIIIIIIIIlIIllIIIIlIllIlllllIlllllllIIlllllllIlIllIlIIlIlIIlIlllIIlIIlIIllIllIIIlIIlIIIIlIlIIlllllIIIIIIlIlllIllllIIlIIIllIIIlIIllIlIIIlll() {
        return this.llIllIIlIIIIlllIIlllIlIlIIIllIIllllIlIlIIllIIlIIIIIlllIIlIlIlIlIIIlIlIllIllIIllIIllIIllIIIIlIIlIllIIlIllIIIIllIIlllllllIlIllIIIlIIIIIlIllIIIIlllllIIlIIlIlllIIlIlIlIIlIIlIlIIIlIlIIlIllIIlllIIIIllIlIIlI;
    }

    public int IIIllIlIIIIlllllIlIIIlllIIlIlIIlIIlIIIllIllIlllIllIllIlIIlIIllIlIIlIIIIlIlIIllIIIIlIIIllIIIllIllllllIIIIIIIllIllllllllllllllllllIlllIlIIIllIIIIIlIIIIlllIIIllllIIIIllIIIIIIIIIlIlIIIllllIlIlIIIllIIIIIII() {
        return this.llIlllIlIllIllIIlIIIIIIIlIIlIIIlIllllIIllIIlIlllllIlllIlllIIIlIlIlllllIlIlIIIllIlIlllllIlIIlIlIIlIlIIlIIllIIIIIIlIlllIIIlIIlllIlIIIlIIlIlllllIlIllIllllIIIIlIIIIllIlIlIlIIllIIIIIIllIIlIIIlIllIIlllIllIl;
    }

    public String IIIIIIlIIIIIIIIllIllllIlIIllIlllIlllllllIlIlIIIlllIIIlIlIIlIIIIlIlllIIIIIIIlIlllIIIIlIlllIIIIlIIlIlIlIIllIIlllIlIlllllIIIIIIIlIlIIlIlllIIIlIlIIIIlIIIIIlIlllllIlIlIIlIlIlIlIlllIlllIlIlIlIlllIllIIlIlIIl() {
        return this.lIIlIlllIlIlIIIIllIlIllIlIlIIlIIlIlIlIlIIllIIlllIIIlIlIlllllIlIIIIIIllIIllllllIllllIIlIIIIllIIIIIIlIIIIlIIIIlIlIIllllIIIIIlllllIlIlllIlIIIIllIIIlllllllllIlIlIllIlllIIIIlIIIlIIIIlIlIlIllIlIllllllIlIlll;
    }

    public Class44 IIlIlllIIlIlIIlIlIIIllIlllIllllIlllIlllIllIllllIllllIIlIIlIIlIlIllllIIIlIlIllIllIIIlIllIlIIIIllIIIIllllIlllIIlllllIllllIllIlIIllIIlIlIIIIllIllIIllllIlIIIlIIIlIlIIlIIIIllIlIIlIIlIlIIlIlIIlIlllIlIlllIll() {
        return this.IIlIllIIIIIlllIIIllIIlIIIllIIIlIlIllIIIlIIlllIIlllllllIlIIIlIlIlllIIIIIIlIIIIlllIlllIlIlIIllIlllIlllllIllIIlIlllIIIllIlIIllllIIlIlIIIIIllllllIIlllIIIlIIllIlIllIIlIllllIlllIIlIIlIIlIlllIlIlIIllIIIIllII;
    }

    public void IlIIIllIIIllIlIlllllIlIIlIllIIlllIIIIIlllllllIIlIlIIllIIllIIIIlIIIlIIIIlllIIlIIlIlllIIlllIlllllIIIllIIIlIIIllIlIIIlIlIllIIlIIIlIlllIllllIIlIlIIIIIlIlllllIIlIIIlIIllIIIIIIIlIIllIIIIIllIIllIIIIllIIIIllI(String string) {
        this.lIIlIlllIlIlIIIIllIlIllIlIlIIlIIlIlIlIlIIllIIlllIIIlIlIlllllIlIIIIIIllIIllllllIllllIIlIIIIllIIIIIIlIIIIlIIIIlIlIIllllIIIIIlllllIlIlllIlIIIIllIIIlllllllllIlIlIllIlllIIIIlIIIlIIIIlIlIlIllIlIllllllIlIlll = string;
    }

    public void lIIIIIlIIIlIlIIlllIIlIllIlllIIIIllIlIlllIIlllIIlIlllIlIIIllIIIlIIllIlIlIIlIIllIllIlIllIllIIlIllllIIIllllIlIIIIIlIlIllIIlIIlIIlIIIllIllllIIIlIlIIlIIllIIIIlIlIIlIlIllIIlllIllllIIIlllllllIlIllIIlIIIIllll(int n) {
        this.llIlllIlIllIllIIlIIIIIIIlIIlIIIlIllllIIllIIlIlllllIlllIlllIIIlIlIlllllIlIlIIIllIlIlllllIlIIlIlIIlIlIIlIIllIIIIIIlIlllIIIlIIlllIlIIIlIIlIlllllIlIllIllllIIIIlIIIIllIlIlIlIIllIIIIIIllIIlIIIlIllIIlllIllIl = n;
    }

    public Class17(String string, int n, Class44 class44) {
        this.lIIlIlllIlIlIIIIllIlIllIlIlIIlIIlIlIlIlIIllIIlllIIIlIlIlllllIlIIIIIIllIIllllllIllllIIlIIIIllIIIIIIlIIIIlIIIIlIlIIllllIIIIIlllllIlIlllIlIIIIllIIIlllllllllIlIlIllIlllIIIIlIIIlIIIIlIlIlIllIlIllllllIlIlll = string;
        this.llIlllIlIllIllIIlIIIIIIIlIIlIIIlIllllIIllIIlIlllllIlllIlllIIIlIlIlllllIlIlIIIllIlIlllllIlIIlIlIIlIlIIlIIllIIIIIIlIlllIIIlIIlllIlIIIlIIlIlllllIlIllIllllIIIIlIIIIllIlIlIlIIllIIIIIIllIIlIIIlIllIIlllIllIl = n;
        this.IIlIllIIIIIlllIIIllIIlIIIllIIIlIlIllIIIlIIlllIIlllllllIlIIIlIlIlllIIIIIIlIIIIlllIlllIlIlIIllIlllIlllllIllIIlIlllIIIllIlIIllllIIlIlIIIIIllllllIIlllIIIlIIllIlIllIIlIllllIlllIIlIIlIIlIlllIlIlIIllIIIIllII = class44;
    }

    public void IlIIIllIlllIllllIIllIllIIIlIlIIIllIlIIllllllIllIlIIIIlllllIIllIlllIIlIIIIIIlIllIIIIIlIIIIllIIlIIlIlIIllIIlIlIlIllIlllIIllllIllIIllIIIllIIlIIIlllIlIlIllIlIIIllIIIlIIIlllIlllIlIlIIIllIIlIlIIIIlIIIIIIllI() {
        MinecraftForge.EVENT_BUS.register((Object)this);
    }
}

