/*
 * Decompiled with CFR 0.152.
 */
public final class Class44
extends Enum<Class44> {
    public static final /* enum */ Class44 IlllIlllIIlllIIIIllIIIIlIlllIIIlIlIIlIlllIlIlIlllIIIlIllllIIIlllIlIlIIlllllllIllIllllllIIllIllIIIIIlllllIllllIllIIIIlllIlllIlIlllIllllllIlIIllllllIllllIlIIIllIlllllIIllIlIIllIIlIllIIIlIlllIllIlIllllII;
    public static final /* enum */ Class44 IIlIllIlIlIIIlIlIIlIIlllIIlIlllIllIlllIlllIlIlIlIlIlIIllIIlIIlIlllIIIIllIllIIIIlIllIlIlllllIIlIIlIlIllIllIlIlIIlllIIIlIIIllIlIIIIIIIlIllIllIlIlIIlIllIllIIIIlllIllIIllIlIIIlIllllllIIlIIlIlIlIIIllIIllIl;
    private static final /* synthetic */ Class44[] llIIIIIlIIIlIIIIIlIIIIIlIlIlIlIlIllllIIIlIlIlIlIIlIIIIlIIIIllllIllIlIllIIIllIlIIlIlIIlIIlllllIIlllIIIIllIIlllIIIIIIlIIIIlIllIllIllIIlllIIIlIlIIIIlIlIIIIllIlIllllllIllIIIllIllllllIlIIlIlIlllllIlllIlIll;
    public static final /* enum */ Class44 IllllIlIlllllIlIlllllIIlIlIllIIllllIIlIIllIllllIIIllIlIIIIIlIIlIIllIIllllIlllIllllllIllIIIIIIlIIllIllllIIIlIllIIlIllIlIlIlIlIlIIlIlllllIlIlIlllIllIlIlIllIIlIllIlIlIlIllIlIlllIIIIIIlllIIIlllIlIIIIlIIIl;
    public static final /* enum */ Class44 IlIlllIIlIllllIlIIllIlllIIIIIIIIlllIIlIlIlIlIlIllIlIIllllIIIlIIlllIIIlIIlIIIIllIlllIlIlIIlIlIIIllIIIIlIIIIIllIlIIllIllIlIIllIIlIllllllllIllllIllIIIllllIIIlIlIlIIIlIlIIIlllIlIlllIIllIIIIIIllIlllIlIIIII;
    private static long IlIIllIIIlIllIIllIIIIlllllIIlIIIlllIIlIllllllllIIIlIIlllIIIlllIIllIIIllIIlllIlIlIllllllIllllIlIlIlIIllllIllIIIIIIIlIIIlIlIIlllIlllllIlIIIlIIlIlIlIlllIllllIIllIllIllIllIlIIlIIlllIIllllIlIIIIIIlllIIIIII = -4780962454886765522L;
    public static final /* enum */ Class44 IlIllIllIIlIIlllllIIlIlllIlllIlIIllIIIIIIIIlIlIIIIIIlIlIIIllIllllIlIIlIllIIIlIIlIIlIlIIIlIIIlIlIIlIIlllIllIlllIlIlIIIIlIlllIIllIIIIIlIIllIlllllIlIlIIlIIlIlllIIlIllllIlllIlIIllllllIIlIlIlIllIIlIlIIIlII;

    public static String Deobfuscated_by_tenonteam() {
        return "Deobfuscated by tenonteam";
    }

    public static Class44 IllIIIlllllIIIlIlllIlllIllIIIIIIlIlllllllllIIlIlIIIlIlIllIllllIllIIllIlIIlIlIIllllIIIlllIIIlllIIlIlIlllIIIIIllIllllIIIllllIlllIIlIlIllIIlIlllllIlllIIIllIIlIllIllIllIIlIlIIIlIlIlllllIIIIlllIIIIllIIIlIl(String string) {
        return Enum.valueOf(Class44.class, string);
    }

    static {
        IlIllIllIIlIIlllllIIlIlllIlllIlIIllIIIIIIIIlIlIIIIIIlIlIIIllIllllIlIIlIllIIIlIIlIIlIlIIIlIIIlIlIIlIIlllIllIlllIlIlIIIIlIlllIIllIIIIIlIIllIlllllIlIlIIlIIlIlllIIlIllllIlllIlIIllllllIIlIlIlIllIIlIlIIIlII = new Class44();
        IllllIlIlllllIlIlllllIIlIlIllIIllllIIlIIllIllllIIIllIlIIIIIlIIlIIllIIllllIlllIllllllIllIIIIIIlIIllIllllIIIlIllIIlIllIlIlIlIlIlIIlIlllllIlIlIlllIllIlIlIllIIlIllIlIlIlIllIlIlllIIIIIIlllIIIlllIlIIIIlIIIl = new Class44();
        IlllIlllIIlllIIIIllIIIIlIlllIIIlIlIIlIlllIlIlIlllIIIlIllllIIIlllIlIlIIlllllllIllIllllllIIllIllIIIIIlllllIllllIllIIIIlllIlllIlIlllIllllllIlIIllllllIllllIlIIIllIlllllIIllIlIIllIIlIllIIIlIlllIllIlIllllII = new Class44();
        IIlIllIlIlIIIlIlIIlIIlllIIlIlllIllIlllIlllIlIlIlIlIlIIllIIlIIlIlllIIIIllIllIIIIlIllIlIlllllIIlIIlIlIllIllIlIlIIlllIIIlIIIllIlIIIIIIIlIllIllIlIlIIlIllIllIIIIlllIllIIllIlIIIlIllllllIIlIIlIlIlIIIllIIllIl = new Class44();
        IlIlllIIlIllllIlIIllIlllIIIIIIIIlllIIlIlIlIlIlIllIlIIllllIIIlIIlllIIIlIIlIIIIllIlllIlIlIIlIlIIIllIIIIlIIIIIllIlIIllIllIlIIllIIlIllllllllIllllIllIIIllllIIIlIlIlIIIlIlIIIlllIlIlllIIllIIIIIIllIlllIlIIIII = new Class44();
        llIIIIIlIIIlIIIIIlIIIIIlIlIlIlIlIllllIIIlIlIlIlIIlIIIIlIIIIllllIllIlIllIIIllIlIIlIlIIlIIlllllIIlllIIIIllIIlllIIIIIIlIIIIlIllIllIllIIlllIIIlIlIIIIlIlIIIIllIlIllllllIllIIIllIllllllIlIIlIlIlllllIlllIlIll = new Class44[]{IlIllIllIIlIIlllllIIlIlllIlllIlIIllIIIIIIIIlIlIIIIIIlIlIIIllIllllIlIIlIllIIIlIIlIIlIlIIIlIIIlIlIIlIIlllIllIlllIlIlIIIIlIlllIIllIIIIIlIIllIlllllIlIlIIlIIlIlllIIlIllllIlllIlIIllllllIIlIlIlIllIIlIlIIIlII, IllllIlIlllllIlIlllllIIlIlIllIIllllIIlIIllIllllIIIllIlIIIIIlIIlIIllIIllllIlllIllllllIllIIIIIIlIIllIllllIIIlIllIIlIllIlIlIlIlIlIIlIlllllIlIlIlllIllIlIlIllIIlIllIlIlIlIllIlIlllIIIIIIlllIIIlllIlIIIIlIIIl, IlllIlllIIlllIIIIllIIIIlIlllIIIlIlIIlIlllIlIlIlllIIIlIllllIIIlllIlIlIIlllllllIllIllllllIIllIllIIIIIlllllIllllIllIIIIlllIlllIlIlllIllllllIlIIllllllIllllIlIIIllIlllllIIllIlIIllIIlIllIIIlIlllIllIlIllllII, IIlIllIlIlIIIlIlIIlIIlllIIlIlllIllIlllIlllIlIlIlIlIlIIllIIlIIlIlllIIIIllIllIIIIlIllIlIlllllIIlIIlIlIllIllIlIlIIlllIIIlIIIllIlIIIIIIIlIllIllIlIlIIlIllIllIIIIlllIllIIllIlIIIlIllllllIIlIIlIlIlIIIllIIllIl, IlIlllIIlIllllIlIIllIlllIIIIIIIIlllIIlIlIlIlIlIllIlIIllllIIIlIIlllIIIlIIlIIIIllIlllIlIlIIlIlIIIllIIIIlIIIIIllIlIIllIllIlIIllIIlIllllllllIllllIllIIIllllIIIlIlIlIIIlIlIIIlllIlIlllIIllIIIIIIllIlllIlIIIII};
    }

    public static Class44[] lIlllIlIIIllIIllIllIllIlIllIlllIllIlIIlIlllIIllllllIIIlIllllIIlllIllllIlllIIllIlIIIlllllIllIIIlIlIIllllIIIllllllIlIIlIllIIlIlIllIIIIIlllIlllIlIlIIIlllIIlllIIlllllIIIIlllIlIlIllIlIlIIlIlIIlllIlllIIllIl() {
        return (Class44[])llIIIIIlIIIlIIIIIlIIIIIlIlIlIlIlIllllIIIlIlIlIlIIlIIIIlIIIIllllIllIlIllIIIllIlIIlIlIIlIIlllllIIlllIIIIllIIlllIIIIIIlIIIIlIllIllIllIIlllIIIlIlIIIIlIlIIIIllIlIllllllIllIIIllIllllllIlIIlIlIlllllIlllIlIll.clone();
    }
}

