/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.mojang.blaze3d.matrix.MatrixStack
 *  net.minecraft.client.Minecraft
 *  net.minecraft.client.gui.screen.Screen
 *  net.minecraft.util.text.ITextComponent
 *  net.minecraft.util.text.StringTextComponent
 */
import com.mojang.blaze3d.matrix.MatrixStack;
import java.util.ArrayList;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.util.text.ITextComponent;
import net.minecraft.util.text.StringTextComponent;

public class Class47
extends Screen {
    public static String lIIlIlIIlIIllllllIllllIIlIlllIllIIllIlIlIIIlIIIIIIllIlllIllIIlIIIllIllIllIllIIlIllIlllIllIIlIlIlllIllIIlIIlllIlIllIIlllIIlllIIlIIllIllIllIlIlllIIIIlIllIIIIIlllIIlIIlIlIIlllIllllIlIIIIlIIlllIIlllIIIIIl;
    public int lIIlIIIIllllIlIIIIIlIlIlIIIIlIIIIlIIIllIlIlIllIlllIIIIIllllIlIIlllIllIIIllIlIIlllllllllIlIllIIlllllllIllIlllllIIlIllIlllllIIIIIIlllIIllIIllIIIlIIllIlIlIlIIIIlIlIlllIIlIllIlIlIIIIlIllIIIIllIllIllllIlII;
    public static double llIIIlIlllIllIIlIllIIIlIIlllIIIIllIlIllIIIlIlIlllIIIllllllllllIIlIlIlllllIIIllIIIlIlIlIIlIlIIIlIIIIIIlllIlllIIIlllIIIIIlIIIlIlIlIIIlIIlllllIlllllIllIIIIlllIlllIIIllIIlIlIIIIIIllIlllIIlIlIlllllIlIIlIlI = 200.0;
    public ArrayList<Class0> lIIIllIIIIIIIIlIIllIlIIlllllIIIIIllIllIIlIlIlIIIIllIlIIIIllIIIlIlIlIIlllllIIlIlIIlIlIIIlIllIIlIlIIIlIIIIlIlllIIlIIllIIlllIIlIIIllIlllllIIIllllllIlIIlIIIllIIlIlIlllIIIIlIIllIIIIIIIlIlIllIIIllIIllIIIlll = new ArrayList();
    public static double llllllIlIlIIIIlIIIllIllIIIllIIllIlIlIllIIIlIIlIlIllIllIlllllllIllllIlIIIIIIlIlIllIllIlllIlIllIIIlIlllllIllIIIIlIlllllIIIlllllIlIlIIIlllllIlIlIIlIIllIlIIllIIlllIllllIIllIIllllIllIllIIllIIlIlllllIIIIlll = 50.0;
    private static Class10 IIllIIlIlllIIllllllllIlllllIIIIllIlIllIllIllllIIIIlIllllIIIIIllllllIIIlIllIIlllllIlIIllllIIlIIlIllIIlIIlIIIlIIlIIllIIlIlIllIlIlIlIIIIIllIIlIIlllIlIIIlllIIIllllllllIlIlIIIlIIIlIlIlllIlIIlIlIIlllIIIllII;
    private static long lIIIlIllIlIIIlllIllIlIlIlIIlIlIIIlIIllIIllIlIIlIlllIIllIIlIllIlIIlllIlIIllIlIIllIIlIIlllllIllIIlIllIIIlllIlIIIIlIllllIIIIlIllIIIIIIIlIIlIllllIIIlIlllIIlIIIIIlIIIIllIllIllllIllIllIIIlIlllIIIllIIIllllII = -4407791666349306111L;

    public static String Deobfuscated_by_tenonteam() {
        return "Deobfuscated by tenonteam";
    }

    public boolean func_231045_a_(double d, double d2, int n, double d3, double d4) {
        if (n == 2) {
            llIIIlIlllIllIIlIllIIIlIIlllIIIIllIlIllIIIlIlIlllIIIllllllllllIIlIlIlllllIIIllIIIlIlIlIIlIlIIIlIIIIIIlllIlllIIIlllIIIIIlIIIlIlIlIIIlIIlllllIlllllIllIIIIlllIlllIIIllIIlIlIIIIIIllIlllIIlIlIlllllIlIIlIlI = d;
            llllllIlIlIIIIlIIIllIllIIIllIIllIlIlIllIIIlIIlIlIllIllIlllllllIllllIlIIIIIIlIlIllIllIlllIlIllIIIlIlllllIllIIIIlIlllllIIIlllllIlIlIIIlllllIlIlIIlIIllIlIIllIIlllIllllIIllIIllllIllIllIIllIIlIlllllIIIIlll = d2;
        }
        return super.func_231045_a_(d, d2, n, d3, d4);
    }

    public boolean func_231046_a_(int n, int n2, int n3) {
        for (Class6 class6 : Class0.IlIlIlllllllIlIIIIlIIIIIlllllIlIIllIlllIlllIllIIlIIllllIllIllIlIllIlIllllIllIlIllllllllIIIIllllIIIlIIllllIIIIIllllIIllIlIIIllIIIIIIIlIIIlIllIlIIlIIIIllIllllllIIIIIlllIlIIllIIlllIIllllIllIIllIlIIlIIllI) {
            class6.lIlIIIlIIIIIIIlIlIlllllIlIIlllIllIlIllIlIlIIllllIIllllllllIIIlIIIlllIIlIllIIIIlllIllIIllIIIIIlllIllIlIllllIIIlIIIIIIlIIlIIlIlllIlIIllIIlIIIlIIIllIllIlIIIIllIlllllIlIllllllIllIlIllIllIlIllIIlIlIIllllII(n);
        }
        return super.func_231046_a_(n, n2, n3);
    }

    public void func_230430_a_(MatrixStack matrixStack, int n, int n2, float f) {
        this.func_230446_a_(matrixStack);
        Minecraft.func_71410_x().field_71466_p.func_238421_b_(matrixStack, "4x1 [UNDETECTED] - Created by bush1root", 10.0f, 10.0f, Class38.lIlIIlIlIlllllIlllllIIllIlIlIIllIlIlllIlIIIlIIllIIIlIlIIllllIlIlIllIIIllIIlllIIIlIIIlIlIIIllllllllIIllIlIlIIlllIlllIIIIIIIlIllIIllIIlIllllIIIIlIIlIlIIIlIlIlIlIIIlIllIlIIllIllIIIlIIlllIIlllIIIIlIIlllll.getRGB());
        Class27.lllIIllllIllllIIlIIIIlllIlllIIIIllIlllIlIlIIllIlIlIIlIIIIllIIlIlIIIlIlIlIlIlIllIIlIlIllIlIIllIlIIIIIIIlIlllllIIIlIIIlIIllIlllIlIIllIIllllIlllIllIllIIlIllllIIlIIIlIIllIlIIIIIlIlllllIIllIIIlIllIlIIlIIll(matrixStack, (float)llIIIlIlllIllIIlIllIIIlIIlllIIIIllIlIllIIIlIlIlllIIIllllllllllIIlIlIlllllIIIllIIIlIlIlIIlIlIIIlIIIIIIlllIlllIIIlllIIIIIlIIIlIlIlIIIlIIlllllIlllllIllIIIIlllIlllIIIllIIlIlIIIIIIllIlllIIlIlIlllllIlIIlIlI, (float)llllllIlIlIIIIlIIIllIllIIIllIIllIlIlIllIIIlIIlIlIllIllIlllllllIllllIlIIIIIIlIlIllIllIlllIlIllIIIlIlllllIllIIIIlIlllllIIIlllllIlIlIIIlllllIlIlIIlIIllIlIIllIIlllIllllIIllIIllllIllIllIIllIIlIlllllIIIIlll, (float)(llIIIlIlllIllIIlIllIIIlIIlllIIIIllIlIllIIIlIlIlllIIIllllllllllIIlIlIlllllIIIllIIIlIlIlIIlIlIIIlIIIIIIlllIlllIIIlllIIIIIlIIIlIlIlIIIlIIlllllIlllllIllIIIIlllIlllIIIllIIlIlIIIIIIllIlllIIlIlIlllllIlIIlIlI + 400.0), (float)(llllllIlIlIIIIlIIIllIllIIIllIIllIlIlIllIIIlIIlIlIllIllIlllllllIllllIlIIIIIIlIlIllIllIlllIlIllIIIlIlllllIllIIIIlIlllllIIIlllllIlIlIIIlllllIlIlIIlIIllIlIIllIIlllIllllIIllIIllllIllIllIIllIIlIlllllIIIIlll + 220.0), Class38.lIIIlIlIIIIIIllllIlllIlIIlIlIIllllIlIlIlllIlllIIIIIIllIlIllIlIIIIIlllllIlIIIIIllIlIIlIIlIIllIlIlIlIlllllllllIIllllIIIllIIlIlIIlIIIIlIIIIIIIlIIlllIIllllIIlIIIIlIlllllllllIIlIlllIlllllllIIlIIllIllIlIlIl.getRGB());
        this.lIIIllIIIIIIIIlIIllIlIIlllllIIIIIllIllIIlIlIlIIIIllIlIIIIllIIIlIlIlIIlllllIIlIlIIlIlIIIlIllIIlIlIIIlIIIIlIlllIIlIIllIIlllIIlIIIllIlllllIIIllllllIlIIlIIIllIIlIlIlllIIIIlIIllIIIIIIIlIlIllIIIllIIllIIIlll.clear();
        int n3 = (int)(llllllIlIlIIIIlIIIllIllIIIllIIllIlIlIllIIIlIIlIlIllIllIlllllllIllllIlIIIIIIlIlIllIllIlllIlIllIIIlIlllllIllIIIIlIlllllIIIlllllIlIlIIIlllllIlIlIIlIIllIlIIllIIlllIllllIIllIIllllIllIllIIllIIlIlllllIIIIlll + 35.0);
        for (Class44 class44 : Class44.lIlllIlIIIllIIllIllIllIlIllIlllIllIlIIlIlllIIllllllIIIlIllllIIlllIllllIlllIIllIlIIIlllllIllIIIlIlIIllllIIIllllllIlIIlIllIIlIlIllIIIIIlllIlllIlIlIIIlllIIlllIIlllllIIIIlllIlIlIllIlIlIIlIlIIlllIlllIIllIl()) {
            this.lIIIllIIIIIIIIlIIllIlIIlllllIIIIIllIllIIlIlIlIIIIllIlIIIIllIIIlIlIlIIlllllIIlIlIIlIlIIIlIllIIlIlIIIlIIIIlIlllIIlIIllIIlllIIlIIIllIlllllIIIllllllIlIIlIIIllIIlIlIlllIIIIlIIllIIIIIIIlIlIllIIIllIIllIIIlll.add(new Class0((int)(llIIIlIlllIllIIlIllIIIlIIlllIIIIllIlIllIIIlIlIlllIIIllllllllllIIlIlIlllllIIIllIIIlIlIlIIlIlIIIlIIIIIIlllIlllIIIlllIIIIIlIIIlIlIlIIIlIIlllllIlllllIllIIIIlllIlllIIIllIIlIlIIIIIIllIlllIIlIlIlllllIlIIlIlI + 25.0), n3, 57, 22, class44));
            n3 += 22;
        }
        this.lIIlIIIIllllIlIIIIIlIlIlIIIIlIIIIlIIIllIlIlIllIlllIIIIIllllIlIIlllIllIIIllIlIIlllllllllIlIllIIlllllllIllIlllllIIlIllIlllllIIIIIIlllIIllIIllIIIlIIllIlIlIlIIIIlIlIlllIIlIllIlIlIIIIlIllIIIIllIllIllllIlII = n3;
        for (Class0 class0 : this.lIIIllIIIIIIIIlIIllIlIIlllllIIIIIllIllIIlIlIlIIIIllIlIIIIllIIIlIlIlIIlllllIIlIlIIlIlIIIlIllIIlIlIIIlIIIIlIlllIIlIIllIIlllIIlIIIllIlllllIIIllllllIlIIlIIIllIIlIlIlllIIIIlIIllIIIIIIIlIlIllIIIllIIllIIIlll) {
            class0.llIlIIIlllllllllIIIIIIllIIIlIIlIlIIIIIIlIlIlllIlllIlIIIIlIIIlIIlIIlIlIIlIlllllIlIlIIllIIIlIlllIIllIlllIllIIlIllIlllIllllIIIIlIllIlllllIllIIIIlIIlIIIIIlllllIIlllIIlIllIIlIlIIllIIIlIIlIIIIIlIllIIIlllIII(matrixStack);
        }
        Class27.lllIIllllIllllIIlIIIIlllIlllIIIIllIlllIlIlIIllIlIlIIlIIIIllIIlIlIIIlIlIlIlIlIllIIlIlIllIlIIllIlIIIIIIIlIlllllIIIlIIIlIIllIlllIlIIllIIllllIlllIllIllIIlIllllIIlIIIlIIllIlIIIIIlIlllllIIllIIIlIllIlIIlIIll(matrixStack, (float)llIIIlIlllIllIIlIllIIIlIIlllIIIIllIlIllIIIlIlIlllIIIllllllllllIIlIlIlllllIIIllIIIlIlIlIIlIlIIIlIIIIIIlllIlllIIIlllIIIIIlIIIlIlIlIIIlIIlllllIlllllIllIIIIlllIlllIIIllIIlIlIIIIIIllIlllIIlIlIlllllIlIIlIlI, (float)llllllIlIlIIIIlIIIllIllIIIllIIllIlIlIllIIIlIIlIlIllIllIlllllllIllllIlIIIIIIlIlIllIllIlllIlIllIIIlIlllllIllIIIIlIlllllIIIlllllIlIlIIIlllllIlIlIIlIIllIlIIllIIlllIllllIIllIIllllIllIllIIllIIlIlllllIIIIlll, (float)(llIIIlIlllIllIIlIllIIIlIIlllIIIIllIlIllIIIlIlIlllIIIllllllllllIIlIlIlllllIIIllIIIlIlIlIIlIlIIIlIIIIIIlllIlllIIIlllIIIIIlIIIlIlIlIIIlIIlllllIlllllIllIIIIlllIlllIIIllIIlIlIIIIIIllIlllIIlIlIlllllIlIIlIlI + 400.0), (float)(llllllIlIlIIIIlIIIllIllIIIllIIllIlIlIllIIIlIIlIlIllIllIlllllllIllllIlIIIIIIlIlIllIllIlllIlIllIIIlIlllllIllIIIIlIlllllIIIlllllIlIlIIIlllllIlIlIIlIIllIlIIllIIlllIllllIIllIIllllIllIllIIllIIlIlllllIIIIlll + 35.0), Class38.lIIIlIlIIIIIIllllIlllIlIIlIlIIllllIlIlIlllIlllIIIIIIllIlIllIlIIIIIlllllIlIIIIIllIlIIlIIlIIllIlIlIlIlllllllllIIllllIIIllIIlIlIIlIIIIlIIIIIIIlIIlllIIllllIIlIIIIlIlllllllllIIlIlllIlllllllIIlIIllIllIlIlIl.getRGB());
        Class27.lllIIllllIllllIIlIIIIlllIlllIIIIllIlllIlIlIIllIlIlIIlIIIIllIIlIlIIIlIlIlIlIlIllIIlIlIllIlIIllIlIIIIIIIlIlllllIIIlIIIlIIllIlllIlIIllIIllllIlllIllIllIIlIllllIIlIIIlIIllIlIIIIIlIlllllIIllIIIlIllIlIIlIIll(matrixStack, (float)llIIIlIlllIllIIlIllIIIlIIlllIIIIllIlIllIIIlIlIlllIIIllllllllllIIlIlIlllllIIIllIIIlIlIlIIlIlIIIlIIIIIIlllIlllIIIlllIIIIIlIIIlIlIlIIIlIIlllllIlllllIllIIIIlllIlllIIIllIIlIlIIIIIIllIlllIIlIlIlllllIlIIlIlI, (float)(llllllIlIlIIIIlIIIllIllIIIllIIllIlIlIllIIIlIIlIlIllIllIlllllllIllllIlIIIIIIlIlIllIllIlllIlIllIIIlIlllllIllIIIIlIlllllIIIlllllIlIlIIIlllllIlIlIIlIIllIlIIllIIlllIllllIIllIIllllIllIllIIllIIlIlllllIIIIlll + 185.0), (float)(llIIIlIlllIllIIlIllIIIlIIlllIIIIllIlIllIIIlIlIlllIIIllllllllllIIlIlIlllllIIIllIIIlIlIlIIlIlIIIlIIIIIIlllIlllIIIlllIIIIIlIIIlIlIlIIIlIIlllllIlllllIllIIIIlllIlllIIIllIIlIlIIIIIIllIlllIIlIlIlllllIlIIlIlI + 400.0), (float)(llllllIlIlIIIIlIIIllIllIIIllIIllIlIlIllIIIlIIlIlIllIllIlllllllIllllIlIIIIIIlIlIllIllIlllIlIllIIIlIlllllIllIIIIlIlllllIIIlllllIlIlIIIlllllIlIlIIlIIllIlIIllIIlllIllllIIllIIllllIllIllIIllIIlIlllllIIIIlll + 220.0), Class38.lIIIlIlIIIIIIllllIlllIlIIlIlIIllllIlIlIlllIlllIIIIIIllIlIllIlIIIIIlllllIlIIIIIllIlIIlIIlIIllIlIlIlIlllllllllIIllllIIIllIIlIlIIlIIIIlIIIIIIIlIIlllIIllllIIlIIIIlIlllllllllIIlIlllIlllllllIIlIIllIllIlIlIl.getRGB());
        IIllIIlIlllIIllllllllIlllllIIIIllIlIllIllIllllIIIIlIllllIIIIIllllllIIIlIllIIlllllIlIIllllIIlIIlIllIIlIIlIIIlIIlIIllIIlIlIllIlIlIlIIIIIllIIlIIlllIlIIIlllIIIllllllllIlIlIIIlIIIlIlIlllIlIIlIlIIlllIIIllII = new Class10((int)(llIIIlIlllIllIIlIllIIIlIIlllIIIIllIlIllIIIlIlIlllIIIllllllllllIIlIlIlllllIIIllIIIlIlIlIIlIlIIIlIIIIIIlllIlllIIIlllIIIIIlIIIlIlIlIIIlIIlllllIlllllIllIIIIlllIlllIIIllIIlIlIIIIIIllIlllIIlIlIlllllIlIIlIlI + 25.0), (int)(llllllIlIlIIIIlIIIllIllIIIllIIllIlIlIllIIIlIIlIlIllIllIlllllllIllllIlIIIIIIlIlIllIllIlllIlIllIIIlIlllllIllIIIIlIlllllIIIlllllIlIlIIIlllllIlIlIIlIIllIlIIllIIlllIllllIIllIIllllIllIllIIllIIlIlllllIIIIlll + 185.0), 57, 22);
        IIllIIlIlllIIllllllllIlllllIIIIllIlIllIllIllllIIIIlIllllIIIIIllllllIIIlIllIIlllllIlIIllllIIlIIlIllIIlIIlIIIlIIlIIllIIlIlIllIlIlIlIIIIIllIIlIIlllIlIIIlllIIIllllllllIlIlIIIlIIIlIlIlllIlIIlIlIIlllIIIllII.IlIIIlIIlIIllIllIIIlIIIlIIllIlIIIIIlIllllIlIlIIlIlIIIIlIllIllIIIlIlIllIIIlIllIIlIIlIIlIIIllIIlIIlIIIllIlIlllIIlIIIlIIlIllIIIIllllIIIIlIlIlllllIIllllllIllllIIllIllllIIIllllllIIIIlIlIIllIIlIIIlIIIlIIIll(matrixStack);
        super.func_230430_a_(matrixStack, n, n2, f);
    }

    public boolean func_231043_a_(double d, double d2, double d3) {
        for (Class0 class0 : this.lIIIllIIIIIIIIlIIllIlIIlllllIIIIIllIllIIlIlIlIIIIllIlIIIIllIIIlIlIlIIlllllIIlIlIIlIlIIIlIllIIlIlIIIlIIIIlIlllIIlIIllIIlllIIlIIIllIlllllIIIllllllIlIIlIIIllIIlIlIlllIIIIlIIllIIIIIIIlIlIllIIIllIIllIIIlll) {
            class0.IlIllIIIlllIlllIIIllIIlIlllIlllIllllIIIlllllIIIlIlIlIlIIllIIllIlllllllIlIllIllIllIIIllIllIllIIIIIIlIIIlllIllIlIIllIlIlIIlllIllIIllIIllllIlIIIIllIIlIIllIllIllIlIIlIllIIlIIlIlIIIIlllIlIIlIIllIIllllllIll(d3);
        }
        return super.func_231043_a_(d, d2, d3);
    }

    public Class47() {
        super((ITextComponent)new StringTextComponent("4x1"));
    }

    public void func_212927_b(double d, double d2) {
        super.func_212927_b(d, d2);
    }

    public boolean func_231044_a_(double d, double d2, int n) {
        for (Class0 object : this.lIIIllIIIIIIIIlIIllIlIIlllllIIIIIllIllIIlIlIlIIIIllIlIIIIllIIIlIlIlIIlllllIIlIlIIlIlIIIlIllIIlIlIIIlIIIIlIlllIIlIIllIIlllIIlIIIllIlllllIIIllllllIlIIlIIIllIIlIlIlllIIIIlIIllIIIIIIIlIlIllIIIllIIllIIIlll) {
            object.IllllIlllIlIllIlllIIlIIlIIlIIIIlllIlllIIlllIIlIlIllIIIllIlllllIlIIllIIlIlIlIlIllIlIIIlIllIIlIIIIIIlIIlIlllIlllIIIIIIlllIIlllllIlIIIIIIllIIIIIIlIIIIIllIllIlIlllIlIIIIlIllIlllIlllIlllIIlIIlIllllllIIIIlI(d, d2, n);
        }
        for (Class6 class6 : Class0.IlIlIlllllllIlIIIIlIIIIIlllllIlIIllIlllIlllIllIIlIIllllIllIllIlIllIlIllllIllIlIllllllllIIIIllllIIIlIIllllIIIIIllllIIllIlIIIllIIIIIIIlIIIlIllIlIIlIIIIllIllllllIIIIIlllIlIIllIIlllIIllllIllIIllIlIIlIIllI) {
            class6.IlIlIIIIIlIlIIIllIIlIIlIlIlIllIlllIIIIllllIIlIIIIllIlllIlllllIlIIlllIIIIlIIIIIIlIlIIlllIlllIlIllllllIIIIIlIIIIlIIlIlllIIllIlIIlIlllIlllIIIIlIIIlllIllIlIIIllIllIIIIIIIllIIlIIIlIlIllIlIIlllllIlIlllIIIIl(d, d2, n);
        }
        IIllIIlIlllIIllllllllIlllllIIIIllIlIllIllIllllIIIIlIllllIIIIIllllllIIIlIllIIlllllIlIIllllIIlIIlIllIIlIIlIIIlIIlIIllIIlIlIllIlIlIlIIIIIllIIlIIlllIlIIIlllIIIllllllllIlIlIIIlIIIlIlIlllIlIIlIlIIlllIIIllII.IIIIIIIlIlIIIlllIIIIllIllIIIIlIIllIIllIIIIIIllllIlllIIIlIllIIllllIlIllIIIIllIIllIIIIlIlIllIIlIlIIIllIlIIllIlllIlIIllIIllIllIIIIIIIIIIlIllllllIlIllllIIIIlIIllIIIIIlllIlIlIIlllIlIlIlIIIIIIIlIIlIIIlIlIII(d, d2, n);
        return super.func_231044_a_(d, d2, n);
    }

    public void func_231160_c_() {
    }

    public void func_231175_as__() {
        super.func_231175_as__();
    }
}

