/*
 * Decompiled with CFR 0.152.
 */
import java.util.ArrayList;

public class Class13 {
    private String llIllllIIlIllIllIIIllIIIllIlllllIIIIlIIIIIIlIIIllIIIIllllIlllIlllIllIIlIIIIlIIlIIlIIlIIllIIllIIIIlllllllIIIllIIIllIIIlIlllIlllllIlIllIlIllllIlllIIlllIIIIIlIIIllIIllIlIIIlllIIIllIIlIIIIlIIIlIIIIlIlIIIl;
    private ArrayList<String> IIllIllIIIIIIllIIllllllIIlIIlIIlIlIIIllIlIlllIlIIIlllIIllIlllIIIlIIllIllIlIIIllIIIIlIIIlIIlIlIIlIlIIIllIIIlIIIlIllIlIIlIlIlllIIlllIllIlllIllllIIIIIlIlllllIIIIlIllIIlIIllIllIIlIIIIIIIIIlllIIllIIllllIll;
    private boolean llIlllIIIIllIIIIllIIlIIllllIlIlIIlIIIIlllIIlIllIIllIIlllIlIIllIlIIIIlIlIlIIIlIlIllllIIlIIIIIlIllIlIIlIlIIlIlIllIIIllllIIllllIIlllIIIlIlIlIlIlIllIlIllIlIllllIIIIlllllIIIlIlllIllIlIlIlIlIIIllIIIllIIIlll;
    private String lIIlllIlllIlIIIlIIlIIlllIlIlllIIIlIlIIlIlIIIllIllIIllIIlIIlIlllIlIllIllIlllIlllllIIlIIlIIIlIllIllIlIIIIIlllIlIIlIIllIIlIlIlIIIlllIIllIIllIIllIIlllIlllIlIIllIIIlIlIIllllIIIlllIIIIIllIlllIIIIlIIllIlIIIl;
    private double IlIllIlIlIllIllIlllIIllllIllIllIllIIIlIllllIllllIIlIIIlIlIIIllllIIlIlIlIlIlIIlllIllIIIllIlllIIIlIIIIIIIlIlllIllIllIlIllIlIIIIlIlIllllllIIIllIIllIIllIlllIlllIlIIIIllllIlIIlllIIIlIlllIlIlIlllIllIlIllIIl;
    private boolean lIlIllIllIIllIllIlllllIllIllIIlIIlllllIlllIIIlllllllIllIIlIIIlIlIlIIlIlIllIlIllIlIllllIlllIIlIIIlllIIllIIllIlIllIIlIIlIlIIlIlIIlllIllllIIIlIIlIlIllIlIllIIIllIIIlIIIlIIlIIIlllllIlIIIlllllIllIlIllIlllIl = false;
    private double lllIIIIIlllIIIIllIlIIIllIIIIIIIlIIIIIlllIIllllllllllllIlllIIlllIlIIlIllIllIIIlIIIllIIIIllllIIlllIlIIllIIlllIllIlllIIlllIIIlIllIIlIIIIIIIIIlIlllIllIIlIlIlllIlllllIlIlIlIllIlIlllIIlIIlIIIlIIIlllllllIIIl;
    private double lllIIlIIIIIIIIllIllIIIIIIllIllIIIllllIllIIllIlIIIlIIlIlIIIlIllllllIlIlIIlIlIIlIlllIIIIlIlllIIIIIlIlllIIIllIIlllIIlIIIIIIIlIlIIllIIlIIIlIIIlIIIIIlIIIllllIIllIIIlllIIllIlIlllllllllIlllIIIIIlIllIlllIIlIl;
    private String lIIlIllIlIIllllIlIIllIIllIIlIIIlllIllllllllIIIIIlllIlIlIIlIIIllIllIIllIIlllIIlllllllIlIlIlIlIlllIlIIlllIlllllIlllIIlIlllIIIIlIIlIIllllIlIlIlIlIlIIIIlllIIllIllllIIllIIIIlIlIIIlllIlllIlIIIIlIllIIIlIlIlI;
    private static long llIIIlIIIIlllIlIlllIlIIllllIllllIIlllIllllllIIIlIlllllllIllIIllIlIIlIIIIIlllIIIlllIlIIIlllIIIllIlllIllllIlIlIIIIIIIllIIllIllllIlllIIlllllllIIllIllIIIllIlllllIlIIIIlllllIIlllIlIlllllIIlIIlIIIIIlllIllll = 2689575226797481739L;
    private Class17 IIIllIIllllIIIIlllIlllIlIIlIIllIlIIIllllIllIlIIIlIlIllIllIIIllIllIIlllIlIlIIllIIlIlIlIIIllIllIIIIIIllIlllIlIIIIIlIlIllIllIIIlIIIIlllIIIllIIlIllIIIllIIllIllllIIIIllllllIlllIIlIlIlIIIIIlIllIIlIIlIIIllll;
    private String llIlIIIlIllllIlIlIIlIlIIlllIllIIIIIIIllIIIllIIIlIIIIlIllIlIlIIllIIIlllllllIIlIlllIlIlIllIllllIllIllllIlIIIIIlIIlIIIIIIIIlllIIIlllIIlllIIIIIIIIlllIlIIIlllIlllllIIIlIllllllIIIlIIIlIIIlllllIIIIlllllllIIl;
    private int llllIlIIlIllIllllllllIllllllllllIIIlIIlllIIlIIIlIllIIIIlIllIlIllIIllllIlIIIllIllIlIIIlIllIIIIIIlIlIIlIllllIlIllIllIlllIIIIIIlIlIIlIIIlllIlIllIllIlIIIlllllllIIIIIIllllIIlIlIllllIlIlIlIIIIlllIlIIllIlllI;
    private String lIlIlIllIlllIIIlllIIIlllIlIlIIlIIllIIIlllIlIlIIlIIIIIIllIIIllIllIlIIIIlIIIIlllIIIllIlllIllIIIIIIllllIIIIlIIlIIlIllIlIlIIlIIllIIIIlIlIllIIllIIIlIllllIIIIIllllIIlIIIlIIlIIllIIIIllIllIlIlIlIIllIIIIllIlll;

    public static String Deobfuscated_by_tenonteam() {
        return "Deobfuscated by tenonteam";
    }

    public Class13(String string, Class17 class17, ArrayList<String> arrayList, String string2) {
        this.llIlIIIlIllllIlIlIIlIlIIlllIllIIIIIIIllIIIllIIIlIIIIlIllIlIlIIllIIIlllllllIIlIlllIlIlIllIllllIllIllllIlIIIIIlIIlIIIIIIIIlllIIIlllIIlllIIIIIIIIlllIlIIIlllIlllllIIIlIllllllIIIlIIIlIIIlllllIIIIlllllllIIl = string;
        this.IIIllIIllllIIIIlllIlllIlIIlIIllIlIIIllllIllIlIIIlIlIllIllIIIllIllIIlllIlIlIIllIIlIlIlIIIllIllIIIIIIllIlllIlIIIIIlIlIllIllIIIlIIIIlllIIIllIIlIllIIIllIIllIllllIIIIllllllIlllIIlIlIlIIIIIlIllIIlIIlIIIllll = class17;
        this.IIllIllIIIIIIllIIllllllIIlIIlIIlIlIIIllIlIlllIlIIIlllIIllIlllIIIlIIllIllIlIIIllIIIIlIIIlIIlIlIIlIlIIIllIIIlIIIlIllIlIIlIlIlllIIlllIllIlllIllllIIIIIlIlllllIIIIlIllIIlIIllIllIIlIIIIIIIIIlllIIllIIllllIll = arrayList;
        this.llIllllIIlIllIllIIIllIIIllIlllllIIIIlIIIIIIlIIIllIIIIllllIlllIlllIllIIlIIIIlIIlIIlIIlIIllIIllIIIIlllllllIIIllIIIllIIIlIlllIlllllIlIllIlIllllIlllIIlllIIIIIlIIIllIIllIlIIIlllIIIllIIlIIIIlIIIlIIIIlIlIIIl = string2;
        this.lIlIlIllIlllIIIlllIIIlllIlIlIIlIIllIIIlllIlIlIIlIIIIIIllIIIllIllIlIIIIlIIIIlllIIIllIlllIllIIIIIIllllIIIIlIIlIIlIllIlIlIIlIIllIIIIlIlIllIIllIIIlIllllIIIIIllllIIlIIIlIIlIIllIIIIllIllIlIlIlIIllIIIIllIlll = "Combo";
    }

    public int llllIllIllIllIIlIlIlIlIlIllllllIlIlllIIlIIlIllIIlIIIIIllIlIIIIlIIlIIllIlllllllIlIllIllllIlIIlIIllllIllIllIIlllIIlIlIlIIllIIIllIlIIIIlIllllIIIlIllIllIllllIIIIllIlIlllIlIlIIllIlIIlIlIIIIIlIllllIlIlIIIlI() {
        return this.llllIlIIlIllIllllllllIllllllllllIIIlIIlllIIlIIIlIllIIIIlIllIlIllIIllllIlIIIllIllIlIIIlIllIIIIIIlIlIIlIllllIlIllIllIlllIIIIIIlIlIIlIIIlllIlIllIllIlIIIlllllllIIIIIIllllIIlIlIllllIlIlIlIIIIlllIlIIllIlllI;
    }

    public Class13(String string, Class17 class17, boolean bl) {
        this.llIlIIIlIllllIlIlIIlIlIIlllIllIIIIIIIllIIIllIIIlIIIIlIllIlIlIIllIIIlllllllIIlIlllIlIlIllIllllIllIllllIlIIIIIlIIlIIIIIIIIlllIIIlllIIlllIIIIIIIIlllIlIIIlllIlllllIIIlIllllllIIIlIIIlIIIlllllIIIIlllllllIIl = string;
        this.IIIllIIllllIIIIlllIlllIlIIlIIllIlIIIllllIllIlIIIlIlIllIllIIIllIllIIlllIlIlIIllIIlIlIlIIIllIllIIIIIIllIlllIlIIIIIlIlIllIllIIIlIIIIlllIIIllIIlIllIIIllIIllIllllIIIIllllllIlllIIlIlIlIIIIIlIllIIlIIlIIIllll = class17;
        this.llIlllIIIIllIIIIllIIlIIllllIlIlIIlIIIIlllIIlIllIIllIIlllIlIIllIlIIIIlIlIlIIIlIlIllllIIlIIIIIlIllIlIIlIlIIlIlIllIIIllllIIllllIIlllIIIlIlIlIlIlIllIlIllIlIllllIIIIlllllIIIlIlllIllIlIlIlIlIIIllIIIllIIIlll = bl;
        this.lIlIlIllIlllIIIlllIIIlllIlIlIIlIIllIIIlllIlIlIIlIIIIIIllIIIllIllIlIIIIlIIIIlllIIIllIlllIllIIIIIIllllIIIIlIIlIIlIllIlIlIIlIIllIIIIlIlIllIIllIIIlIllllIIIIIllllIIlIIIlIIlIIllIIIIllIllIlIlIlIIllIIIIllIlll = "Check";
    }

    public boolean lIlllIIlllIIIIlIllIlIlIllIIIlIIllIIIIllIlIlllllIIlIlllIlllIllllIllIIIlIllIIIllIlIllIlllIllIlIlllIIIIllIlIIIllllIIlIIIIIIllIlIIlIlIlIIllllIllllIlIIIlllIIlIIlIlIIIlIllIllIlIllllIIlIlllllIlIIIllIIlIIIIII() {
        return this.lIlIlIllIlllIIIlllIIIlllIlIlIIlIIllIIIlllIlIlIIlIIIIIIllIIIllIllIlIIIIlIIIIlllIIIllIlllIllIIIIIIllllIIIIlIIlIIlIllIlIlIIlIIllIIIIlIlIllIIllIIIlIllllIIIIIllllIIlIIIlIIlIIllIIIIllIllIlIlIlIIllIIIIllIlll.equalsIgnoreCase("Check");
    }

    public Class17 llIllIllllllIlllIIlIlIlIlllIIIIIlIIIlIIIlllllIlllIIIIlIIllllIlIIlIlIIIlIIlllIIIIIlIlIIlIIlIIlIIIIlIllIllIIllIlIIIIIIIIllllllIllIllllllllIIlllIllIIlIlIllllllIlIIlllIIIIlIllIlIlIIIlIIlIIllIllIIIIIlllIIl() {
        return this.IIIllIIllllIIIIlllIlllIlIIlIIllIlIIIllllIllIlIIIlIlIllIllIIIllIllIIlllIlIlIIllIIlIlIlIIIllIllIIIIIIllIlllIlIIIIIlIlIllIllIIIlIIIIlllIIIllIIlIllIIIllIIllIllllIIIIllllllIlllIIlIlIlIIIIIlIllIIlIIlIIIllll;
    }

    public String IlIlIIlIllIlllllllIIIlIllIllIIIlIIIIIIIIIIIlIIllIllIlllIllIIIIllIIIlIlIllllIllIlIIIlIIIlIIIIllllIllIllllllIIlIllIllIIllllIllIIlIIIlIIllllllIIlllIllIlIIIlIIlllIIIlIlIIlIlIIIlIlIlllllIllIIIlllIIIIIIIllI() {
        return this.llIllllIIlIllIllIIIllIIIllIlllllIIIIlIIIIIIlIIIllIIIIllllIlllIlllIllIIlIIIIlIIlIIlIIlIIllIIllIIIIlllllllIIIllIIIllIIIlIlllIlllllIlIllIlIllllIlllIIlllIIIIIlIIIllIIllIlIIIlllIIIllIIlIIIIlIIIlIIIIlIlIIIl;
    }

    public boolean lIlIlIIIIIllllIlIIlllllIIIIlIIIIIllIlIIlIIIlIIIIlIIIllIllllIIIlllIIllIIllllIlIllIIIIIlIIIllIIlIlIIIIIlIIlIlIlllIIIIIlllIIIIlIIlIIllIIIIIlllIllIllIIIlIllllIlIlIlIllllllllIIlllIIlIlIlllIIlIIlllIIlIIIlII() {
        return this.llIlllIIIIllIIIIllIIlIIllllIlIlIIlIIIIlllIIlIllIIllIIlllIlIIllIlIIIIlIlIlIIIlIlIllllIIlIIIIIlIllIlIIlIlIIlIlIllIIIllllIIllllIIlllIIIlIlIlIlIlIllIlIllIlIllllIIIIlllllIIIlIlllIllIlIlIlIlIIIllIIIllIIIlll;
    }

    public Class13(String string, Class17 class17, double d, double d2, double d3, boolean bl) {
        this.llIlIIIlIllllIlIlIIlIlIIlllIllIIIIIIIllIIIllIIIlIIIIlIllIlIlIIllIIIlllllllIIlIlllIlIlIllIllllIllIllllIlIIIIIlIIlIIIIIIIIlllIIIlllIIlllIIIIIIIIlllIlIIIlllIlllllIIIlIllllllIIIlIIIlIIIlllllIIIIlllllllIIl = string;
        this.IIIllIIllllIIIIlllIlllIlIIlIIllIlIIIllllIllIlIIIlIlIllIllIIIllIllIIlllIlIlIIllIIlIlIlIIIllIllIIIIIIllIlllIlIIIIIlIlIllIllIIIlIIIIlllIIIllIIlIllIIIllIIllIllllIIIIllllllIlllIIlIlIlIIIIIlIllIIlIIlIIIllll = class17;
        this.IlIllIlIlIllIllIlllIIllllIllIllIllIIIlIllllIllllIIlIIIlIlIIIllllIIlIlIlIlIlIIlllIllIIIllIlllIIIlIIIIIIIlIlllIllIllIlIllIlIIIIlIlIllllllIIIllIIllIIllIlllIlllIlIIIIllllIlIIlllIIIlIlllIlIlIlllIllIlIllIIl = d;
        this.lllIIIIIlllIIIIllIlIIIllIIIIIIIlIIIIIlllIIllllllllllllIlllIIlllIlIIlIllIllIIIlIIIllIIIIllllIIlllIlIIllIIlllIllIlllIIlllIIIlIllIIlIIIIIIIIIlIlllIllIIlIlIlllIlllllIlIlIlIllIlIlllIIlIIlIIIlIIIlllllllIIIl = d2;
        this.lllIIlIIIIIIIIllIllIIIIIIllIllIIIllllIllIIllIlIIIlIIlIlIIIlIllllllIlIlIIlIlIIlIlllIIIIlIlllIIIIIlIlllIIIllIIlllIIlIIIIIIIlIlIIllIIlIIIlIIIlIIIIIlIIIllllIIllIIIlllIIllIlIlllllllllIlllIIIIIlIllIlllIIlIl = d3;
        this.lIlIllIllIIllIllIlllllIllIllIIlIIlllllIlllIIIlllllllIllIIlIIIlIlIlIIlIlIllIlIllIlIllllIlllIIlIIIlllIIllIIllIlIllIIlIIlIlIIlIlIIlllIllllIIIlIIlIlIllIlIllIIIllIIIlIIIlIIlIIIlllllIlIIIlllllIllIlIllIlllIl = bl;
        this.lIlIlIllIlllIIIlllIIIlllIlIlIIlIIllIIIlllIlIlIIlIIIIIIllIIIllIllIlIIIIlIIIIlllIIIllIlllIllIIIIIIllllIIIIlIIlIIlIllIlIlIIlIIllIIIIlIlIllIIllIIIlIllllIIIIIllllIIlIIIlIIlIIllIIIIllIllIlIlIlIIllIIIIllIlll = "Slider";
    }

    public String lIIlllIllIIIlIIlIIllIlIlIlIllIIlIIlIIlllIllIlIllllllIllIIlIIlllllIllIIIllllllIlIIIIllllIIIIllIlllIlIlIIIIIlIllIlIIIIIIIlIIIlIIIIIllllllIIlIIlIlIllIlIIlIllIIIIllIllIIIIIIIlIIlllIlIlIllllIllllIIIllIIIII() {
        return this.lIIlllIlllIlIIIlIIlIIlllIlIlllIIIlIlIIlIlIIIllIllIIllIIlIIlIlllIlIllIllIlllIlllllIIlIIlIIIlIllIllIlIIIIIlllIlIIlIIllIIlIlIlIIIlllIIllIIllIIllIIlllIlllIlIIllIIIlIlIIllllIIIlllIIIIIllIlllIIIIlIIllIlIIIl;
    }

    public void IlllIIIlIllIIllllIIlllIlIlllllIllIlIIIlIIIIIIlllIIllIllIlIllIIIlIlIlIIllIIlIIlIIllIllIlllIIlIIllIIlIIIIlIIllIlIlIlllIIlIlIllIIlIIllIIIIIIIIlIIIIIlllIIIIIlIlIllIlIIIllIlIlIlIlIIIlIlllIlIIIIIlllIllIIIlI(double d) {
        this.IlIllIlIlIllIllIlllIIllllIllIllIllIIIlIllllIllllIIlIIIlIlIIIllllIIlIlIlIlIlIIlllIllIIIllIlllIIIlIIIIIIIlIlllIllIllIlIllIlIIIIlIlIllllllIIIllIIllIIllIlllIlllIlIIIIllllIlIIlllIIIlIlllIlIlIlllIllIlIllIIl = d;
    }

    public double IIIIlIlllllIIlIllllIIlIIIlllIIIIllIIIlIIllIlIIIIllllIlIlIllIlIlIlllllIIIlIIlIlIlIlIllIlIllIlllIIIlllIllIIlIllIlllIIIlIIllIIIlllllIIlIIIIlllIIIlllIlIIIIIIlIIIlIIlIlIIIIlIIIlllIlIlIlllIIIllIllIlIlllllIl() {
        return this.lllIIlIIIIIIIIllIllIIIIIIllIllIIIllllIllIIllIlIIIlIIlIlIIIlIllllllIlIlIIlIlIIlIlllIIIIlIlllIIIIIlIlllIIIllIIlllIIlIIIIIIIlIlIIllIIlIIIlIIIlIIIIIlIIIllllIIllIIIlllIIllIlIlllllllllIlllIIIIIlIllIlllIIlIl;
    }

    public boolean IlIlIlIIlIIIIIlllIIIlllllIlIIlllIllIIIIIlllllIlIIIllIllIlllIlIlIIllllIlIlIllIlIIllIIIIlIIllIIllIIIlllIlIIllIllIIllIIlIlIlIllllIllIllIllIlIIlIIIlIlllIlIllIlllllIIlIlIIlIIlIlIIllIlIIIIllIlllIIIIIIllllll() {
        return this.lIlIlIllIlllIIIlllIIIlllIlIlIIlIIllIIIlllIlIlIIlIIIIIIllIIIllIllIlIIIIlIIIIlllIIIllIlllIllIIIIIIllllIIIIlIIlIIlIllIlIlIIlIIllIIIIlIlIllIIllIIIlIllllIIIIIllllIIlIIIlIIlIIllIIIIllIllIlIlIlIIllIIIIllIlll.equalsIgnoreCase("Combo");
    }

    public double llllIlIIIIIIlIIIlIIIlIllIlIllIIIlllIlIlIIIIIlllIIlIlllIlllIIIIlIIIlIllIlIllllIIlIlllIIIIIIlIlIIlIllIIlIllllIllIIIlIlllIIllIIIllllllIllIIIIIIllllllIlIlIIlIIllIllIlIIllIIlIIIIIlIIIlIIIlllIlIIlIlIllllIIl() {
        if (this.lIlIllIllIIllIllIlllllIllIllIIlIIlllllIlllIIIlllllllIllIIlIIIlIlIlIIlIlIllIlIllIlIllllIlllIIlIIIlllIIllIIllIlIllIIlIIlIlIIlIlIIlllIllllIIIlIIlIlIllIlIllIIIllIIIlIIIlIIlIIIlllllIlIIIlllllIllIlIllIlllIl) {
            this.IlIllIlIlIllIllIlllIIllllIllIllIllIIIlIllllIllllIIlIIIlIlIIIllllIIlIlIlIlIlIIlllIllIIIllIlllIIIlIIIIIIIlIlllIllIllIlIllIlIIIIlIlIllllllIIIllIIllIIllIlllIlllIlIIIIllllIlIIlllIIIlIlllIlIlIlllIllIlIllIIl = (int)this.IlIllIlIlIllIllIlllIIllllIllIllIllIIIlIllllIllllIIlIIIlIlIIIllllIIlIlIlIlIlIIlllIllIIIllIlllIIIlIIIIIIIlIlllIllIllIlIllIlIIIIlIlIllllllIIIllIIllIIllIlllIlllIlIIIIllllIlIIlllIIIlIlllIlIlIlllIllIlIllIIl;
        }
        return this.IlIllIlIlIllIllIlllIIllllIllIllIllIIIlIllllIllllIIlIIIlIlIIIllllIIlIlIlIlIlIIlllIllIIIllIlllIIIlIIIIIIIlIlllIllIllIlIllIlIIIIlIlIllllllIIIllIIllIIllIlllIlllIlIIIIllllIlIIlllIIIlIlllIlIlIlllIllIlIllIIl;
    }

    public boolean lllIllIlIlIIllIIIIlIlllIlllIlllIlIlIllllIIllllllIIIIlIIlllIIllIllIlIIIIIIIllIIIIlllllIIlIlIlIIIlIllIlllIlllIlIIlllIlIlIIIlIlIllIIlllIlllIlIllIIIIllIlIllllIIlIlIlllIlllIIIlIllllllllIIlllIIllIIllllIIllI() {
        return this.lIlIlIllIlllIIIlllIIIlllIlIlIIlIIllIIIlllIlIlIIlIIIIIIllIIIllIllIlIIIIlIIIIlllIIIllIlllIllIIIIIIllllIIIIlIIlIIlIllIlIlIIlIIllIIIIlIlIllIIllIIIlIllllIIIIIllllIIlIIIlIIlIIllIIIIllIllIlIlIlIIllIIIIllIlll.equalsIgnoreCase("Slider");
    }

    public double lllIIIIIllIIlIlIlllIIIlIlIlllIIllIIlIIlllIIlllIlIlIIlllllIllIllllIIlIlIIlIIllIlllIIIIlIIllllllIlIllIIIIlIlIIIlIIlIIlllllIIIlIIIIlIIIlIlIIlllIlIIIIIIlllIIlIIIlIlIIlIIIIIIIlllIlIIllIIlllIIIllIIIllIlllll() {
        return this.lllIIIIIlllIIIIllIlIIIllIIIIIIIlIIIIIlllIIllllllllllllIlllIIlllIlIIlIllIllIIIlIIIllIIIIllllIIlllIlIIllIIlllIllIlllIIlllIIIlIllIIlIIIIIIIIIlIlllIllIIlIlIlllIlllllIlIlIlIllIlIlllIIlIIlIIIlIIIlllllllIIIl;
    }

    public String IIlIIllIlIllIIIllIllIIIllIlIIlIIllllllIIIIllIllIllIllIllIIlIllIIlIIIIllIIlIllIlIIlllIIIllIlllIIllllllIllIIIlllIIllIIllIIIIlIllIIIllllIlIlIIlllIllIlIIllIIIIlIllllIlIIllIllIlIIlIIllIIlIlIlIIIlllIIlIIlII() {
        return this.lIIlIllIlIIllllIlIIllIIllIIlIIIlllIllllllllIIIIIlllIlIlIIlIIIllIllIIllIIlllIIlllllllIlIlIlIlIlllIlIIlllIlllllIlllIIlIlllIIIIlIIlIIllllIlIlIlIlIlIIIIlllIIllIllllIIllIIIIlIlIIIlllIlllIlIIIIlIllIIIlIlIlI;
    }

    public boolean IIlllIIIIllIIlIIllIlllIIIIIlllllIlIlIlllllllIllllIllIIIIllIIllIlIllllIlIIIIllIIIlllIlIlllIIIlIlIIlllIIlIIlIlIIllIlIIlllIlllllllIlIllllIllIIIIIIlIIlIIlIIIlllIlIlIlIlIlIllIIIllllllIIlIlIIIIIIIIIIlIlIllI() {
        return this.lIlIlIllIlllIIIlllIIIlllIlIlIIlIIllIIIlllIlIlIIlIIIIIIllIIIllIllIlIIIIlIIIIlllIIIllIlllIllIIIIIIllllIIIIlIIlIIlIllIlIlIIlIIllIIIIlIlIllIIllIIIlIllllIIIIIllllIIlIIIlIIlIIllIIIIllIllIlIlIlIIllIIIIllIlll.equalsIgnoreCase("ModeButton");
    }

    public ArrayList<String> lllIIIIIllIIllIllIIllIllllllIlllIIllIllllllIIIIIllIIlIlIlllllIlIIIlllIIIlIIIIllllIIlllIIIlIlIIIllllllIlllIIlIllIllllIIIIlIlllIllIIIIlllIllIIIlIlIllIIIIIlIIlIllIllIIIlllllllIIIllIllllIIlIIlllllIIIllIlI() {
        return this.IIllIllIIIIIIllIIllllllIIlIIlIIlIlIIIllIlIlllIlIIIlllIIllIlllIIIlIIllIllIlIIIllIIIIlIIIlIIlIlIIlIlIIIllIIIlIIIlIllIlIIlIlIlllIIlllIllIlllIllllIIIIIlIlllllIIIIlIllIIlIIllIllIIlIIIIIIIIIlllIIllIIllllIll;
    }

    public boolean lIlIlIlIIIllIlIlIlIllIIlIlIlIIIIIlIIllIIllIIllIIIIlllIIIIllIllllIIlIIllIllIIlIIlIIIlIlIlIlIIlIlIlIllIIllllIllIllIllIlIIIIIIIlllllllllIlIIIIllllllIIlIlIIIllIIIIIllllIllllIlIIlIIIlllIllIIllIlIlllIlIIlll() {
        return this.lIlIllIllIIllIllIlllllIllIllIIlIIlllllIlllIIIlllllllIllIIlIIIlIlIlIIlIlIllIlIllIlIllllIlllIIlIIIlllIIllIIllIlIllIIlIIlIlIIlIlIIlllIllllIIIlIIlIlIllIlIllIIIllIIIlIIIlIIlIIIlllllIlIIIlllllIllIlIllIlllIl;
    }

    public void IIllIIllIIIllllllllIIIIIIlIlIIlIllIllIlIlIIlIlIIIllllIIlIllIIIllllllIIIlIIIlIIllIIIlIllllllIlIllllIIIlIIIllIIllllllllIlIlIlllllllIIIllllIIllllIIIllIIIlIllIIlIIlIlllIlIIIIIlIIlIlIlllIIlIlIIlIllllIIIllI(boolean bl) {
        this.llIlllIIIIllIIIIllIIlIIllllIlIlIIlIIIIlllIIlIllIIllIIlllIlIIllIlIIIIlIlIlIIIlIlIllllIIlIIIIIlIllIlIIlIlIIlIlIllIIIllllIIllllIIlllIIIlIlIlIlIlIllIlIllIlIllllIIIIlllllIIIlIlllIllIlIlIlIlIIIllIIIllIIIlll = bl;
    }

    public void llIlIIlIllIIIllllIlIlIIIllIIIllIIIIllllllIIlIIlllIIlIIllIlIlIlIllIlllllllIlllIIllIllIIIIIIIIIIlIIIllIIlllIIIIlIIIlIlllIllllIlIIIIlIIIllIlIlIlIIlIIIIlIlIIllIIIllllIIIIlIIIllIlIIlIllllIlllIIllIIIIlIlIll(String string) {
        this.lIIlIllIlIIllllIlIIllIIllIIlIIIlllIllllllllIIIIIlllIlIlIIlIIIllIllIIllIIlllIIlllllllIlIlIlIlIlllIlIIlllIlllllIlllIIlIlllIIIIlIIlIIllllIlIlIlIlIlIIIIlllIIllIllllIIllIIIIlIlIIIlllIlllIlIIIIlIllIIIlIlIlI = string;
    }

    public String lIIlllIlIlIIIllIIlIllIIllllIIlIIlIIllIIIllIIlllIIIIIlIllIlIIlIIlllIIlIIIIIIlIIIIllIIIIIIlIIllllIIIIIIlllIIlIIlIIIlIllllIlIlIlllIlIllIlIllIIIIlIIIllIIlIIllIIIllllIIIlIllIllIlIllIIlllIIIIIlllIlIIlIllIIl() {
        return this.llIlIIIlIllllIlIlIIlIlIIlllIllIIIIIIIllIIIllIIIlIIIIlIllIlIlIIllIIIlllllllIIlIlllIlIlIllIllllIllIllllIlIIIIIlIIlIIIIIIIIlllIIIlllIIlllIIIIIIIIlllIlIIIlllIlllllIIIlIllllllIIIlIIIlIIIlllllIIIIlllllllIIl;
    }
}

